version: '3.9'

networks:
  chat-gpt-network:
    name:
      "chat_gpt_network"
    ipam:
      config:
        - subnet: 200.20.0.0/24

services:

  bot:
    image: "chat_gpt_bot_service:latest"
    container_name: "chat_gpt_bot_service"
    hostname: "bot_service"
    build:
      context: .
      dockerfile: deploy/Dockerfile
      target: bot-service
      args:
        STAGE: ${STAGE}
    restart: unless-stopped
    env_file:
      - bot_microservice/settings/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      chat-gpt-network:
        ipv4_address: 200.20.0.10
    expose:
      - "8000"
    command: bash start-bot.sh

  chat-gpt:
    image: "fantasypeak/freegpt:latest"
    container_name: "chat_gpt_chat_service"
    hostname: "chat_service"
    restart: unless-stopped
    environment:
      CHAT_PATH: "/gpt/chat"
    volumes:
      - ./chat_gpt_microservice/client:/app/client
    networks:
      chat-gpt-network:
        ipv4_address: 200.20.0.11
    expose:
      - "8858"

  caddy:
    image: "caddy:2.7.4"
    container_name: "chat_gpt_caddy_service"
    hostname: "caddy_service"
    restart: unless-stopped
    ports:
      - '8083:8083'
      - '8084:8084'
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      chat-gpt-network:
        ipv4_address: 200.20.0.12
