version: '3.9'

networks:
  chatgpt-network:
    name:
      "chatgpt_network"
    ipam:
      config:
        - subnet: 200.20.0.0/24

services:

  bot:
    image: "chatgpt_bot_service:latest"
    container_name: "chatgpt_bot_service"
    hostname: "bot_service"
    build:
      context: .
      dockerfile: deploy/Dockerfile
      target: bot-service
      args:
        STAGE: ${STAGE:-production}
    restart: unless-stopped
    env_file:
      - bot_microservice/settings/.env
    volumes:
      - ./bot_microservice/settings:/app/settings:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      chatgpt-network:
        ipv4_address: 200.20.0.10
    expose:
      - "8000"
    command: bash start-bot.sh

  chatgpt_chat:
    image: "balshdocker/freegpt:latest"
    container_name: "chatgpt_chat_service"
    hostname: "chatgpt_chat_service"
    restart: unless-stopped
    environment:
      CHAT_PATH: "/gpt/chat"
      API_KEY: "a40f22f2-c1a2-4b1d-a47f-55ae1a7ddbed"
    networks:
      chatgpt-network:
        ipv4_address: 200.20.0.11
    expose:
      - "8858"

  caddy:
    image: "caddy:2.7.4"
    container_name: "chatgpt_caddy_service"
    hostname: "caddy_service"
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8084:8084"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      chatgpt-network:
        ipv4_address: 200.20.0.12
