[tool.poetry]
name = "healthcheck_bot"
version = "0.7.1"
description = "Bot to help with mosgortans"
authors = ["Dmitry Afanasyev <Balshbox@gmail.com>"]

[tool.poetry.dependencies]

fastapi = "^0.101"
python-telegram-bot = {version = "^20.5", extras=["ext"]}

python = "^3.11"
python-dotenv = "^1.0"
httpx = "^0.24"
loguru = "^0.7"
pydantic = "^2.3"
gunicorn = "^21.2"
uvicorn = "^0.23"
wheel = "^0.41"
orjson = "^3.9"

websocket-client = "^1.6"
requests = "^2.31"
selenium = "^4.11"
tls-client = "^0.2"
pypasser = "^0.0.5"
names = "^0.3"
colorama = "^0.4"
curl_cffi = "^0.5"
aiohttp = "^3.8.5"
flask = "^2.3"
flask_cors = "^4.0"
flask-babel = "^3.1"
streamlit = "^1.26"
fake-useragent = "^1.2"
twocaptcha = "^0.0.1"
pymailtm = "^1.1"
Levenshtein = "^0.21"
retrying = "^1.3"
mailgw_temporary_email = "^0.0.2"
pycryptodome = "^3.18"
random-password-generator = "^2.2"
numpy = "^1.25"
tornado = "^6.3"
PyExecJS = "^1.5"
browser_cookie3 = "^0.19"

[tool.poetry.dev-dependencies]

factory-boy = "^3.3"
Faker = "^19"

ipython = "^8.14"

safety = "^2.3"
pip-audit = "^2.6"
yamllint = "^1.32"
tomlkit = "^0.12"
bandit = "^1.7"
aresponses = "^2.1"

pyupgrade = "^3.10"
isort = "^5.12"
black = "^23.3"

mypy = "^1.5"
types-PyMySQL = "^1.0"
types-python-dateutil = "^2.8"

pytest = "^7.4"
pytest-asyncio = "^0.21"
pytest-deadfixtures = "^2.2"
pytest-repeat = "^0.9"
pytest-testmon = "^2.0"
pytest-mock = "^3.11"
pytest-cov = "^4.1"
pytest-timeout = "^2.1"
pytest-timeouts = "^1.2"
pytest-sugar = "^0.9"
pytest-clarity = "^1.0"
pytest-env = "^0.8"
nest-asyncio = "^1.5"
pytest-html = "^3.2"
pytest-randomly = "^3.15"
pytest-split = "^0.8"
pytest-freezegun = "^0.4"
pytest-socket = "^0.6"
assertpy = "^1.1"

coverage = "^7.3"

autoflake = "2.2"
flake8 = "^6.1"
flake8-logging-format = "^0.9"
flake8-comprehensions = "^3.14"
flake8-eradicate = "^1.5"
flake8-deprecated = "^2.0"
flake8-pytest-style = "^1.7"
flake8-aaa = "^0.16"
flake8-bugbear = "^23.7"
flake8-warnings = "^0.4"
flake8-debugger = "^4.1"
flake8-annotations-complexity = "^0.0.8"
flake8-fixme = "^1.1"
flake8-simplify = "^0.20"
flake8-variables-names = "^0.0.6"
flake8-bandit = "^4.1"
flake8-tidy-imports = "^4.10"
flake8-noqa = "^1.3"
flake8-useless-assert = "^0.4"
flake8-mock = "^0.4"
flake8-jira-todo-checker = "^0.6"
flake8-comments = "^0.1"
flake8-newspaper-style = "^0.4"


[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["app", "settings", "tests"]
combine_as_imports = true


[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false


[tool.coverage.run]
relative_files = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py311']
