"""initial migration

Revision ID: 0001_create_chatgpt_table
Revises:
Create Date: 2023-10-05 18:28:30.915361

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_create_chatgpt_table"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatgpt",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("model", sa.VARCHAR(length=256), nullable=False),
        sa.Column("priority", sa.SMALLINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chatgpt")
    # ### end Alembic commands ###
