"""add_last_question_at

Revision ID: 0004_add_last_question_at
Revises: 0003_create_user_question_count_table
Create Date: 2024-01-08 20:56:34.815976

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0004_add_last_question_at"
down_revision = "0003_create_user_question_count_table"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_token_created_at", table_name="access_token")
    op.add_column("user_question_count", sa.Column("last_question_at", sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_question_count", "last_question_at")
    op.create_index("ix_access_token_created_at", "access_token", ["created_at"], unique=False)
    # ### end Alembic commands ###
