version: "3.9"

networks:
  chat_gpt_network:
    name: "chat_gpt_network"

services:

  chat-gpt-caddy:
    image: caddy:2.7.4
    container_name: "chat_gpt_caddy"
    restart: unless-stopped
    networks:
      - chat_gpt_network
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8081:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/localtime:/etc/localtime:ro

  chat-gpt:
    image: balsh_chat_gpt:latest #ramonvc/freegpt-webui:latest
    container_name: "chat_gpt"
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "chat_gpt"
    networks:
      - chat_gpt_network
    volumes:
      - ./client:/client
    depends_on:
      - chat-gpt-caddy
    expose:
      - "1338"
    restart: unless-stopped